

name: Sending-Current-Stock-Prices-With-Line

on:
  schedule:
  # scheduled at every 30min during trading hours, (UTC+8), weekdays
    - cron: "0,30 1,2,3,4,5 * * 1,2,3,4,5"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.8'
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run Python Code
        env:
          FUGLE_API_TOKEN: ${{ secrets.FUGLE_API_TOKEN }}
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        run: python sending_current_stock_prices_with_line.py
